### ISSUE TITLE
No ability to provision release profiles with preferred words

### ISSUE THREAD

**Issue by n4zmz** [devopsarr/terraform-provider-sonarr#263]
Not that I needed these until recently when I changed my configuration to include x265 over 264 using preferred words.

**Comment by Fuochi** [comment]
Hi @n4zmz,
I'm sorry but I'm following Sonarr v4 version for this provider development.
The preferred words feature has been removed when they introduced custom formats here: https://github.com/Sonarr/Sonarr/commit/b04b4000b84a8a3ea8bb7b784fbbf9ff08451c6e

I know that v4 is still in beta, but they added the API description through swagger file, which is required for this project, in v4 only. Hence, this v3 feature will not be implemented.
Again, sorry.
