### ISSUE TITLE
Resource Type Not Found for qbittorrent and sabnzbd with provider version 3.1.0

### ISSUE THREAD

**Issue by tinhtruong** [devopsarr/terraform-provider-sonarr#295]
When I was trying to provision Sonarr with the provider version 3.1.0, I've got error 

> ╷
│ Error: Resource Type Not Found
│
│   with sonarr_download_client_qbittorrent.qbittorrent,
│   on main.tf line 6, in resource "sonarr_download_client_qbittorrent" "qbittorrent":
│    6: resource "sonarr_download_client_qbittorrent" "qbittorrent" {
│
│ No resource type named "sonarr_download_client_qbittorrent" was found in the provider.
╵
╷
│ Error: Resource Type Not Found
│
│   with sonarr_download_client_sabnzbd.sabnzbd,
│   on main.tf line 21, in resource "sonarr_download_client_sabnzbd" "sabnzbd":
│   21: resource "sonarr_download_client_sabnzbd" "sabnzbd" {
│
│ No resource type named "sonarr_download_client_sabnzbd" was found in the provider.

When I downgraded the provider to version 3.0.0. Everything works fine.

My setup:
Terraform: 1.6.1
Sonarr: 3.0.10.1567
OS: Archlinux

**Comment by Fuochi** [comment]
Hi @tinhtruong thanks for pointing this out. It seems you matched the criteria for this terraform bug: https://github.com/hashicorp/terraform-plugin-framework/issues/853
It's already fixed in main branch after the dependency update in 88a1a27 to their hotfix, In the next release it will work!

**Comment by tinhtruong** [comment]
@Fuochi thanks!
I am looking forward to test the new release.
Cheers

**Comment by Fuochi** [comment]
Hi @tinhtruong, version 3.1.1 is live, could you please confirm it works as expected?

**Comment by tinhtruong** [comment]
@Fuochi 
I tried with version 3.1.1 and it works properly now.
Thanks for the fix.
