### ISSUE TITLE
sonarr_quality_definition is missing preferred_size

### ISSUE THREAD

**Issue by pedorich-n** [devopsarr/terraform-provider-sonarr#341]
It seems like the `radarr` provider [supports it](https://github.com/devopsarr/terraform-provider-radarr/blob/8d0cc003b053677bfec57487f7524855d4aab183/internal/provider/quality_definition_resource.go#L42), so should be easy to add, I hope.
Here's the API definition: https://github.com/Sonarr/Sonarr/blob/5d1d44e09ef43754f91484846ca0313bd0eb0baf/src/Sonarr.Api.V3/openapi.json#L10738

**Comment by Fuochi** [comment]
Hi @pedorich-n,
Thanks for opening the issue, could you please check v3.4.0?

**Comment by pedorich-n** [comment]
It works.
Thanks!
